# Generated by Django 6.0 on 2026-01-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_mentors_studentprofile_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='pending_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
