# Generated by Django 6.0.2 on 2026-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_pending_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional summary', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education_details',
            field=models.TextField(blank=True, help_text='e.g. B.Tech in Computer Science', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_csv',
            field=models.CharField(blank=True, help_text='Comma separated skills like: Django, React, Python', max_length=500, null=True),
        ),
    ]
