# Generated by Django 6.0.2 on 2026-03-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_studentprofile_portfolio_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='job_title',
            field=models.CharField(blank=True, default='Software Developer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Gandhinagar, Gujarat, India', max_length=200, null=True),
        ),
    ]
