# Generated by Django 6.0.3 on 2026-04-30 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_staffprofile'),
        ('students', '0013_add_indexes_and_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='sp_mentor_public_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='students_bl_student_9d9795_idx',
            old_name='blog_student_created_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='students_bl_is_priv_e19a89_idx',
            old_name='blog_private_created_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='students_ce_student_7d65e5_idx',
            old_name='cert_student_created_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='students_pr_student_f34cd3_idx',
            old_name='proj_student_created_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='students_pr_is_veri_de9c60_idx',
            old_name='proj_verified_public_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='students_st_college_25a69c_idx',
            old_name='sp_college_semester_idx',
        ),
        migrations.RenameIndex(
            model_name='todoitem',
            new_name='students_to_student_34390f_idx',
            old_name='todo_student_status_idx',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='education_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills_csv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['mentor', '-is_profile_public'], name='students_st_mentor__d02d0a_idx'),
        ),
    ]
