# Generated by Django 6.0.3 on 2026-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='students_pr_student_f34cd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='students_pr_is_veri_de9c60_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
