# Generated by Django 6.0.3 on 2026-05-14 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_staffprofile'),
        ('students', '0015_remove_project_students_pr_student_f34cd3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('semester', models.IntegerField(db_index=True, default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department')),
                ('hod', models.ForeignKey(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.companyplacement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_registrations', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companyplacement',
            index=models.Index(fields=['department', 'semester', 'is_active'], name='students_co_departm_862898_idx'),
        ),
        migrations.AddIndex(
            model_name='placementregistration',
            index=models.Index(fields=['student', 'placement'], name='students_pl_student_ce7bf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placementregistration',
            unique_together={('student', 'placement')},
        ),
    ]
