# Generated by Django 6.0.2 on 2026-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_todoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['is_completed', 'due_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
