# Generated by Django 6.0.2 on 2026-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_todoitem_options_todoitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='faculty_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='needs_revision',
            field=models.BooleanField(default=False),
        ),
    ]
