# Generated by Django 6.0.2 on 2026-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_project_faculty_remarks_project_needs_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_hero_subtitle',
            field=models.CharField(blank=True, help_text='e.g. I build scalable web apps.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_hero_title',
            field=models.CharField(blank=True, help_text='e.g. Hi, my name is John.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_template',
            field=models.CharField(choices=[('default', 'Minimal Standard'), ('dark_tech', 'Dark Tech (Tailwind)')], default='default', max_length=20),
        ),
    ]
