# Generated by Django 6.0.2 on 2026-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentprofile_portfolio_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='portfolio_hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='portfolio_hero_title',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='portfolio_template',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_theme',
            field=models.CharField(choices=[('modern', 'Modern Business'), ('minimal', 'Clean Minimalist'), ('hacker', 'Terminal Developer')], default='modern', max_length=20),
        ),
    ]
