# Generated by Django 6.0.3 on 2026-04-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_user_id_b37b35_idx',
            old_name='notif_user_created_idx',
        ),
    ]
