# Generated by Django 6.0 on 2025-12-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_staffprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
